### ISSUE TITLE
spell cloud whitelists can be confusing: should we have multiple bundles per spell?

### ISSUE THREAD

**Issue by mikemccracken** [conjure-up/spells#46]
for example the openstack-novalxd bundle is currently restricted to localhost.

IIRC this is mostly because it has no placement directives so it'd take like 16 machines on maas.

however it's also the only spell that gives you an openstack that USES novalxd, which is not good.

two ways to solve this:
1. start another spell for openstack-on-maas-with-novalxd
2. change openstack-novalxd to allow any cloud but just have a different bundle to use for each cloud, so the 'maas' bundle will give you a 4 machine setup

**Comment by ryan-beisner** [comment]
+1 to a MAAS Nova-LXD option, whether that is a new spell or a re-think of how spells/bundles are mapped.

Naturally, all of the special system tuning which is necessary for the *-on-lxd spells would not apply to the *-on-maas spells, so that might be enough of a difference in approach to re-enforce the current 1 spell / 1 bundle mapping.

Seems like it's a matter of clean/clear spells vs. UX flexibility.

**Comment by ryan-beisner** [comment]
Worth cross-referencing https://github.com/conjure-up/spells/issues/44 here.

**Comment by battlemidget** [comment]
closing this out as we're going with a spell per deployment type
